version: '3.8'
services:
  app:
    container_name: flask_api
    image: portianoy/flask_api_task
    ports:
      - "5000:5000"
    restart: always
    environment:
      FLASK_APP: "api.py"
      FLASK_ENVIRONMENT: "development"
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      DB_USERNAME: "devops"
      DB_PASSWORD: "devops"
      DB_HOSTNAME: my_sql_db
      DB_PORT: 3306
      DB_NAME: "student"
    depends_on:
      - my_sql_db
    networks:
      - flask_api

  my_sql_db:
    image: mysql/mysql-server:latest
    container_name: flask_api_db
    ports:
      - "3306:3306"
    volumes:
      - api-db:/var/lib/mysql
      - ./api-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - flask_api
    environment:
      - MYSQL_ROOT_PASSWORD=devops
      - MYSQL_PASSWORD=devops
      - MYSQL_USER=devops
      - MYSQL_DATABASE=student
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      timeout: 20s
      retries: 5
      start_period: 30s

networks:
  flask_api:
    name: flask_api_network
    driver: bridge

volumes:
  api-db: