---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flask-app
  name: flask-app-deployment
  labels:
    name: flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: flask-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: flask-app
      labels:
        name: flask-app
      namespace: flask-app
    spec:
      containers:
        - name: flask-app
          image: portianoy/flask_api_task:latest
          imagePullPolicy: Always
          command: ["python"]
          args: ["-m", "flask", "run", "-h", "0.0.0.0"]
          env:
            - name: FLASK_APP
              value: api.py
            - name: FLASK_ENV
              value: development
            - name: DB_USERNAME
              value: devops
            - name: DB_NAME
              value: student
            - name: DB_HOSTNAME
              value: mysql
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
          resources:
            limits:
              memory: "256Mi"
              cpu: "300m"
            requests:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 5000
              name: flask
          startupProbe:
            httpGet:
              path: /api/health-check/ok
              port: flask
            failureThreshold: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/health-check/ok
              port: flask
            failureThreshold: 5
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: flask-app
spec:
  selector:
    name: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: flask
      name: flask-svc