- hosts: web-server
  remote_user: ubuntu
  become: true

  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        name: "*"
        state: latest

    - name: Install dependencies
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - htop

    - name: Install apt key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
        keyring: /etc/apt/trusted.gpg.d/docker.gpg

    - name: Install docker repo
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install docker
      apt:
        update_cache: yes
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

    - name: Add user to docker group
      remote_user: ubuntu
      user:
        name: "ubuntu"
        group: "docker"
        append: yes

    - name: Reset ssh connection to apply group
      meta:
        reset_connection

    - name: Generate SSH key
      openssh_keypair:
        path: "/home/ubuntu/.ssh/id_rsa"
        type: rsa
        size: 4096
        state: present
        force: no

    - name: Clone project
      git:
        repo: "git@github.com:iportianoy/flask-api-task.git"
        dest: "/home/ubuntu/flask-api-task"
        accept_hostkey: yes
        key_file: "/home/ubuntu/.ssh/id_rsa"

    - name: Run app via shell
      become: true
      shell:
        cmd: "docker compose up -d"
        chdir: "/home/ubuntu/flask-api-task"