name: CI/CD

on:
  push:
    branches:
      - master

env:
  REGISTRY: portianoy/flask_api_task

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: flake8 lint
        uses: py-actions/flake8@v2

  build_and_push:
    runs-on: ubuntu-latest
    name: Build and push docker image
    needs: lint
    outputs:
      commit_hash: ${{ steps.commit_hash.outputs.commit_hash }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - id: commit_hash
        run: echo "::set-output name=commit_hash::${GITHUB_SHA::7}"

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}:${{ steps.commit_hash.outputs.commit_hash }},
            ${{ env.REGISTRY }}:latest

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build_and_push
    env:
      USERNAME: ubuntu
    strategy:
      matrix:
        host: [ 3.66.156.134, 54.93.95.155]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Deploy to EC2 instanse via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ matrix.host }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: ${{ secrets.DOCKER_USER }}, ${{ secrets.DOCKERHUB_TOKEN }}
          port: 22
          script: |
            # login docker
            docker login -u $DOCKER_USER -p $DOCKERHUB_TOKEN
            docker stop flask_api
            docker rm flask_api
            cd flask-api-task
            docker compose down
            docker pull ${{ env.REGISTRY }}:latest
            docker compose up --build -d

  report:
    runs-on: ubuntu-latest
    name: Reports
    strategy:
      matrix:
        host: [ 3.66.156.134, 54.93.95.155 ]
    steps:
      - name: check health
        uses: wei/curl@master
        with:
          args: http://${{ matrix.host }}:5000/api/health-check/ok